# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
# Name:        gc_egdb_set_spidx_gas
# Purpose:
#
# Author:      Geocom Informatik AG
#
# Created:     01.04.2018
# Copyright:   (c) Geocom Informatik AG 2018
#-------------------------------------------------------------------------------




# Variables

def_array=[]

def_array.append(['/DIV/DIMENSION' , 'Polygon' , [1000]])
def_array.append(['/DIV/KONSTRUKTION_FLA' , 'Polygon' , [1000]])
def_array.append(['/DIV/KONSTRUKTION_LIN' , 'Polyline' , [1000]])
def_array.append(['/DIV/KONSTRUKTION_PKT' , 'Point' , [500]])
def_array.append(['/DIV/MESSPUNKT' , 'Point' , [1000]])

def_array.append(['/GAS/GAS_BAUMASSNAHMEN' , 'Point' , [1000]])
def_array.append(['/GAS/GAS_BMN_FLA' , 'Polygon' , [500]])
def_array.append(['/GAS/GAS_BMN_LIN' , 'Polyline' , [250]])
def_array.append(['/GAS/GAS_BMN_PKT' , 'Point' , [250]])
def_array.append(['/GAS/GAS_KABEL_PKT' , 'Point' , [1000]])
def_array.append(['/GAS/GAS_ARMATUR' , 'Point' , [250]])
def_array.append(['/GAS/GAS_KABEL' , 'Polyline' , [250]])
def_array.append(['/GAS/GAS_HYDRAULIK_KNOTEN_PKT' , 'Point' , [1000]])
def_array.append(['/GAS/GAS_HYDRAULIK_STRANG_LIN' , 'Polyline' , [1000]])
def_array.append(['/GAS/GAS_KKS' , 'Point' , [1000]])
def_array.append(['/GAS/GAS_LEITUNG' , 'Polyline' , [200]])
def_array.append(['/GAS/GAS_LEITUNGSPUNKT' , 'Point' , [250]])
def_array.append(['/GAS/GAS_ROHRLEITUNGSTEIL' , 'Point' , [250]])
def_array.append(['/GAS/GAS_LINIE' , 'Polyline' , [500]])
def_array.append(['/GAS/GAS_SBW_FLA' , 'Polygon' , [500]])
def_array.append(['/GAS/GAS_SBW_LIN' , 'Polyline' , [500]])
def_array.append(['/GAS/GAS_SBW_PKT' , 'Point' , [500]])
def_array.append(['/GAS/GAS_TOPO_LIN' , 'Polyline' , [250]])
def_array.append(['/GAS/GAS_SCHADEN' , 'Point' , [500]])
def_array.append(['/GAS/GAS_SIPHON' , 'Point' , [500]])
def_array.append(['/GAS/GAS_SPEZIALBAUWERK' , 'Point' , [1000]])
def_array.append(['/GAS/GAS_UEBRIGE_PKT' , 'Point' , [250]])
def_array.append(['/GAS/GAS_HAUSANSCHLUSS' , 'Point' , [250]])
def_array.append(['/GAS/GAS_NET_Junctions' , 'Point' , [200]])
def_array.append(['/GAS/GAS_DETAILPUNKT' , 'Point' , [500]])
def_array.append(['/GAS/GAS_EINSTIEG' , 'Point' , [500]])

def_array.append(['/GAS_LABEL/GAST_BEMERKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_UEBERDECKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_MATTYPMESS_BMN' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NUMMER_SIPHON' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NUMMER_HYD_STRANG' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NAME_HYD_KNOTEN' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_SCHALT_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_TEXT_KABEL' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NUMMER_HAUSAN' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_NUMMER_ROHRT' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_TEXT' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_TEXT_KABEL_PKT' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GAST_MATDURCH_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_LABEL/GASA_ff410317521b57877244e6e7' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_b1d3543845cc4294291418bf' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_308b897ce42e345121cadbcb' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_773e5ff19458fcaaee358936' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_a0487081e03394363629033f' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_d9d0d50a53fbef13706cf0e9' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_add248e20429ba4b092024e6' , 'Annotation' , [500]])
def_array.append(['/GAS_LABEL/GASA_05e1390a6bb8fe0d1a55f19e' , 'Annotation' , [500]])

def_array.append(['/GAS_PW2/gas_pw2_armatur' , 'Point' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_leitung' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_rohrleitungsteil' , 'Point' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_siphon' , 'Point' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_hausanschluss' , 'Point' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_spezialbauwerk' , 'Point' , [500]])
def_array.append(['/GAS_PW2/gas_pw2_topo_lin' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/GAS_PW2_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PW2/GAS_PW2_KKS' , 'Point' , [500]])
def_array.append(['/GAS_PW2/GAS_PW2_KABEL' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/GAS_PW2_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PW2/GAST_PW2_DURCHM_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/GAST_PW2_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/GAST_PW2_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_PW2/GAST_PW2_NUMMER_SIPHON' , 'Polyline' , [500]])

def_array.append(['/GAS_PW3/gas_pw3_topo_lin' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAST_PW3_DURCHM_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAST_PW3_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAST_PW3_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAST_PW3_NUMMER_SIPHON' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_KABEL' , 'Polyline' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_KKS' , 'Point' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_HAUSANSCHLUSS' , 'Point' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_ROHRLEITUNGSTEIL' , 'Point' , [500]])
def_array.append(['/GAS_PW3/GAS_PW3_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PW3/gas_pw3_armatur' , 'Point' , [500]])
def_array.append(['/GAS_PW3/gas_pw3_siphon' , 'Point' , [1000]])
def_array.append(['/GAS_PW3/gas_pw3_spezialbauwerk' , 'Point' , [1000]])
def_array.append(['/GAS_PW3/gas_pw3_leitung' , 'Polyline' , [250]])

def_array.append(['/GAS_PWD/GAS_PWD_ARMATUR' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_HAUSANSCHLUSS' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_SIPHON' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_KABEL' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_KKS' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_LEITUNG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_ROHRLEITUNGSTEIL' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_SPEZIALBAUWERK' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_BEMERKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_MATDURCH_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_SCHALT_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_UEBERDECKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NUMMER_SIPHON' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NAME_ABBILD' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NAME_URSPRUNG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GNPWD_URSPRUNG' , 'Polygon' , [500]])
def_array.append(['/GAS_PWD/GNPWD_ABBILD' , 'Polygon' , [500]])
def_array.append(['/GAS_PWD/GNPWD_VERBINDUNG' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_SBW_PKT' , 'Point' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_SBW_LIN' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAS_PWD_SBW_FLA' , 'Polygon' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NUMMER_HAUSAN' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GAST_PWD_NUMMER_ROHRT' , 'Polyline' , [500]])
def_array.append(['/GAS_PWD/GASA_a9207562e6becccdaff2482f' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_77e5992a58c97372d07aa11f' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_2a1e72b1d1ca3740a8ffd313' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_3358091c645d9a587ecf3884' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_58e64c726c73d7acf1a903bf' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_8a87d97dfe06598932872ddc' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_624758d70d219b98164027e8' , 'Annotation' , [500]])
def_array.append(['/GAS_PWD/GASA_ae1c5c76d2280d32828a948d' , 'Annotation' , [500]])